### ISSUE TITLE
Decoder und Converter

### ISSUE THREAD

**Issue by J-Paul0815** [jensileinchen/Paxcounter-SDS011-Lora-Umweltsensor#1]
Moin Jens, ich hoffe du nimmst es mir nicht krumm, wenn ich so mit Dir in Kontakt trete und nach Hilfe frage.
Ich bin als LoraWan Newbee deiner Anleitung gefolgt, welche ich die beste Anleitung ist, die ich finden konnte.
Vielen Dank dafür.
Ich konnte der Anleitung folgen bis zum Punkt Decoder und Converter.
Anscheinend gibt es das nicht mehr bei TTN und wurde ersetzt mit Payload formatters.
Vielleicht hast Du eine Idee, wie ich die Daten meines BLE280 zum TTN bekomme.
Die Daten vom BLE280 werden mir am Display angezeigt Temp/Hum/Pres nur als Payload bekomme ich die nicht im TTN.
unter Live Data im TTN sehe ich "Accept join-request" und viele "Forward uplink data message", aber nicht "meine" Daten.
Wäre für jede Hilfe wirklich dankbar.

**Comment by jensileinchen** [comment]
Guten Morgen ! - so hier die ausführliche Antwort. Also - in der neuen TTN v.3 Konsole heisst das nun "payload formatters" -- dort wählst du dann bei "Uplink" den Formatter Typ "Javascript" aus und holst dir bei uns aus dem Repository bei Github den passenden (je nachdem, was du eingestellt hast, packed oder plain --- normalerweise ist dort als default "packed" Decoder ausgewählt) Decoder --- (einfach mit copy und paste den vorgegebenen Teil im Decoder überschreiben) --- nun sollten deine Live-Daten mehr oder weniger im Klartext kommen !  

>>> Decoder Link:  https://github.com/dasdigidings/The_Things_Stack_v3-payload_functions/tree/main/paxcounter

Herzlichen Gruß
jensileinchen

**Comment by J-Paul0815** [comment]
Moin Jens, der Tip war Gold wert, die Daten kommen rein. Vielen Dank. Ich mach hier, wenn es Dir Recht ist, in ein paar Tagen zu.

**Comment by jensileinchen** [comment]
Ja einfach schließen  - super ! gerne – schönen Sonntag

Jens

 

Von: J-Paul0815 ***@***.***> 
Gesendet: Sonntag, 10. Oktober 2021 10:38
An: jensileinchen/Paxcounter-SDS011-Lora-Umweltsensor ***@***.***>
Cc: Jens Nowak ***@***.***>; Comment ***@***.***>
Betreff: Re: [jensileinchen/Paxcounter-SDS011-Lora-Umweltsensor] Decoder und Converter (#1)

 

Moin Jens, der Tip war Gold wert, die Daten kommen rein. Vielen Dank. Ich mach hier, wenn es Dir Recht ist, in ein paar Tagen zu.

**Comment by J-Paul0815** [comment]
Danke nochmal.

**Comment by J-Paul0815** [comment]
Hallo Jens,
Du hattest mir so freundlich geholfen, deswegen frage ich noch einmal nach Deiner Hilfe:
Wie geschrieben, habe ich ja meine Daten vom BLE280 über den packed Payload formatter rein bekommen und auch per mqtt zu meinem iobroker geholt. Lief gut. Heute habe ich einen neues Gerät, auch mit einem payload formatter eingerichtet. Kann nicht sagen, ob das mit meinem Problem zusammen hängt, aber seit dem bekomme ich keine Temp/Huminity/Pressure Daten mehr rein, nur noch pax, ble, port und wifi. Nachgeschaut bei TTN ergab, dass das importierte Formatter JS draussen war. Ich habe es neu importiert, aber es funktioniert nicht mehr. Neu ist auch die Fehlermeldung (gelbes Ausrufezeichen) in Zeile 182:
Too many errors  (55% scanned) Hast du eine Idee? Gab es eine Änderung bei TTN? 
Könnte das hiermit zusammenhängen?
https://www.thethingsnetwork.org/forum/t/error-formatter-script-too-large/49220

**Comment by jensileinchen** [comment]
kann es sein das du bei den beiden Geräten unterschiedliche Software verwendest ?
du kannst einen allgemein gültigen payload decoder für die gesamte application definieren ODER einen, der nur für ein bestimmtes device innerhalb der application gültig ist --- liegt da der fehler ? 
die gräße vom payload decoder haben wir eigentlich so klein gehalten das das laufen sollte (btw, läuft ja bei mir ....)

**Comment by J-Paul0815** [comment]
Ok, ja danke, Wieder einmal ein guter Tip. Entschuldige meine Unwissenheit. Wo ist es bei Dir eingetragen, global, oder direkt im Device? Und das Ausrufezeichen mit "too many errors" hast du auch, aber es funktioniert?

**Comment by jensileinchen** [comment]
da ich in meiner application mehrere tracker benutze liegt der payload-decoder in der application, und bei den devices ist nur ausgewählt "use application payload formatter" -- nein, ein ! habe ich nicht --- sollte das nicht funktionieren bei dir müsste der decoder nochmal überarbeitet werden --- das kann ich selber nicht müsste dann jemand anders ausm team machen ....

es gab eine umstellung beim versionswechsel von v.2.xxx auf v.3.xxx im cyberman-repository, sollte bei dir zwischen den geräten genau das der unterschied sein, so wäre ggf. dort das problem zu suchen. meines wissens wurde dort irgendwas an den ports verdreht, wo die daten auflaufen und ins ttn geschoben werden.

**Comment by J-Paul0815** [comment]
OK, so habe ich es bei mir auch wieder eingestellt und das andere (Test-) Device gelöscht, somit sollte der alte Zustand wieder hergestellt sein und ich werde es beobachten, ob es läuft. Leider habe ich in der Stadt und einem 4,3km entfernten Gateway schlechte Verbindung (rssi -105 - -120) da dauert es manchmal Stunden, bis eine Verbindung hergestellt wurde. Hat das erstmal geklappt, bleibt die Verbindung länger bestehen. Mein bestelltes Gateway sollte morgen ankommen.
![image](https://user-images.githubusercontent.com/51191964/137090563-47a70aad-21c8-4fc9-8e65-e55826955889.png)

**Comment by J-Paul0815** [comment]
Habe das Gateway installiert, den Payload Formatter neu im Device importiert. Das Ausrufezeichen (too many errors) ist geblieben, aber die Daten kommen an. Nochmals vielen Dank für deine Unterstützung, Jens.
